name: "PokeGuesser"
networks:
    pokeguesser_network:
        driver: bridge
services:
    pokeguesser_db:
        image: postgres:16
        container_name: pokeguesser_db
        environment:
            POSTGRES_DB: pokeguesser_db
            POSTGRES_USER: docker_user1234
            POSTGRES_PASSWORD: docker_pass1234
        ports:
            - "5434:5432"
        volumes:
            - pokeguesser_data:/var/lib/postgresql/data
        networks:
            - pokeguesser_network
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U docker_user1234 -d pokeguesser_db"]
            interval: 10s
            timeout: 5s
            retries: 5

    pokeguesser_pogotracker_db:
        image: postgres:16
        container_name: pokeguesser_pogotracker_db
        environment:
            POSTGRES_DB: pokeguesser_pogotracker_db
            POSTGRES_USER: pogo_docker_user1234
            POSTGRES_PASSWORD: pogo_docker_pass1234
        ports:
            - "5435:5432"
        volumes:
            - pogotracker_data:/var/lib/postgresql/data
            - ./pogotracker_seed:/docker-entrypoint-initdb.d
        networks:
            - pokeguesser_network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U pogo_docker_user1234 -d pokeguesser_pogotracker_db",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    pokeguesser_backend:
        build:
            context: ../backend
            dockerfile: ../docker/backend_Dockerfile
        container_name: pokeguesser_backend
        command: /entrypoint.sh
        volumes:
            - ../backend:/app # mount backend/ to /app
            - ../docker/backend_entrypoint.sh:/entrypoint.sh:ro # maps entrypoint script outside app/ dir
        ports:
            - "8085:8085"
        networks:
            pokeguesser_network:
                aliases:
                    - backend
        environment:
            - DJANGO_ENV=docker
        env_file:
            - ../backend/.env.docker
        depends_on:
            pokeguesser_db:
                condition: service_healthy
            pokeguesser_pogotracker_db:
                condition: service_healthy

    pokeguesser_frontend:
        build:
            context: ../frontend
            dockerfile: ../docker/frontend_Dockerfile
        container_name: pokeguesser_frontend
        command: npm start
        volumes:
            - ../frontend:/app
            - /app/node_modules
        ports:
            - "3001:3001"
        networks:
            - pokeguesser_network
        environment:
            - VITE_API_TARGET=http://backend:8085
        depends_on:
            - pokeguesser_backend

volumes:
    pokeguesser_data:
    pogotracker_data:
