CREATE TABLE IF NOT EXISTS pokemon (
	id serial4 NOT NULL,
	created timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"number" int4 NOT NULL,
	"name" varchar(50) NOT NULL,
	gender varchar(10) NOT NULL,
	live bool DEFAULT false NOT NULL,
	shiny bool DEFAULT false NOT NULL,
	shadow bool DEFAULT false NOT NULL,
	shadowshiny bool DEFAULT false NOT NULL,
	type1 varchar(10) NOT NULL,
	type2 varchar(10) NOT NULL,
	attack int4 NOT NULL,
	defense int4 NOT NULL,
	hp int4 NOT NULL,
	catch numeric(5, 2) NOT NULL,
	flee numeric(5, 2) NOT NULL,
	form bool DEFAULT false NOT NULL,
	mega bool DEFAULT false NOT NULL,
	sprite varchar(50) NOT NULL,
	tradable bool DEFAULT true NOT NULL,
	giga bool DEFAULT false NOT NULL,
	generation numeric(2, 1) NOT NULL,
	ses varchar(150) NULL,
	formtype varchar(50) NULL,
	CONSTRAINT pk_pokemon_id PRIMARY KEY (id)
);