# Generated by Django 6.0.1 on 2026-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("live", models.BooleanField()),
                ("mega", models.BooleanField()),
                ("giga", models.BooleanField()),
                ("type1", models.CharField(max_length=10)),
                ("type2", models.CharField(max_length=10)),
                ("sprite", models.CharField(max_length=50)),
                ("generation", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                "db_table": "pokemon",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="DailyPokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(unique=True)),
                ("pokemon", models.IntegerField()),
            ],
            options={
                "db_table": "daily_pokemon",
            },
        ),
    ]
