# Generated by Django 6.0.2 on 2026-02-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('app_name', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['app_name', 'event_type'], name='audit_log_app_nam_78a7eb_idx'), models.Index(fields=['timestamp', 'level'], name='audit_log_timesta_020e4f_idx')],
            },
        ),
    ]
